### ISSUE TITLE
How to use service bindings

### ISSUE THREAD

**Issue by tylerphelan** [pivotal-cf/docs-build-service#116]
Write docs article on `How to use service bindings` with CNBs/TBS (maybe pass on to buildpacks team?)

**Comment by ekcasey** [comment]
@tylerphelan  @mgibson1121 

Any chance we could bump this up the priority queue? Several Java Buildpack workflows that customers care about require service bindings. A non-comprehensive list:
* Connecting to a private Maven Repo
* Connecting to Sonar
* Any integration with a security scanner or APM

It would be nice to have official TBS docs to link to when answering questions about these workflows.
