### ISSUE TITLE
Bundling/configuring k8s resources like Ingress, PVCs, etc.

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/docs-build-service#12]
Wanted to comment on [this pull request about installation without cluttering up a legit conversation](https://github.com/pivotal-cf/docs-build-service/pull/11)

Apologies for interjecting, but I presume the reason [the `nginx-ingress` chart isn't being suggested as an alternative to raw k8s manifests](https://github.com/helm/charts/tree/master/stable/nginx-ingress) is because it requires `helm`, which otherwise wouldn't be a requirement since `pb` uses [`duffle`](https://github.com/pivotal-cf/docs-build-service/blob/master/installing.md#install-pivotal-build-service) for deployments?

The only reason I bring it up is because I imagine having people push plain k8s manifests described in this `README.md` might to lead to drift or confusion, especially with upcoming [k8s API deprecations and whatnot and such](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/).

It might be worth considering, _at some point_, how an Ingress Controller / Ingress (or any collection of k8s resources) could be optionally packaged/versioned/leveraged/etc. [From my very limited understanding of `duffle`, I wonder if those resources could be packaged with the duffle bundle and be (optionally) leveraged by users if they didn't want to manage an Ingress / Ingress Controller / PVC / etc. separately?](https://github.com/deislabs/cnab-spec/issues/175)

Again, don't mean to be obnoxious with unsolicited opinions, just figured I'd share. Obviously zero expectation to respond to this comment, feel free to close this whenever, etc.

**Comment by ashwin-venkatesh** [comment]
I think this is really valuable feedback and we really appreciate you helping us. Currently, we expect users to bring their own ingress controller and we weren't too keen on providing raw k8s manifests(which we did get rid of in favor of a link to pivotal docs which walks through the setup of an ingress controller/service). Presently we are trying to limit the scope of build service but we do see a lot of value in a CNAB bundle that could be used to get an ingress controller up and running.

We want to avoid getting into the business of maintaining documentation on things that aren't build service.

I think the idea of a duffle bundle to install an ingress controller and service is a really great one but would probably be best managed by the PCFS team. We could pair with them initially to help them get bootstrapped but it would be great if we weren't the team responsible for maintaining it.

PVCs are a different situation as it is something you need to configure your k8s cluster with. But I think your point still stands. Let us know if the updates made to the PR are ones that are valuable ones and feel free to open new issues or follow up on existing ones.
