### ISSUE TITLE
The "Search" capability does not seem  to be working for TBS docs

### ISSUE THREAD

**Issue by jgalvin98** [pivotal-cf/docs-build-service#182]
When entering a value into the search bar, the results page always returns "No Results" regardless of the term being searched.  The results page shows that it is "Filtering by: Tanzu Build Service and 1.0"

**Comment by seviet** [comment]
@jgalvin98 search is missing due to the elastic search service not being bound to the build service production doc apps. I've added the service-- search should be available after the next site pushes. cc: @kvedurmu

**Comment by jgalvin98** [comment]
Thanks @seviet, also, just FYI, I noticed that it does not work for any version of the TBS docs.  Will the elastic search binding cover all TBS doc versions? - Thanks!

**Comment by seviet** [comment]
It has to be bound to each doc app, which are currently structured to be a blue/green set for each version of build service. I've bound the service to each individual app, so all versions should have search-enabled after their next production push. cc: @matthewmcnew @mgibson1121

**Comment by seviet** [comment]
Search is enabled on all versions now. Closing...
