### ISSUE TITLE
TKG not referenced in the install overview section

### ISSUE THREAD

**Issue by jgalvin98** [pivotal-cf/docs-build-service#183]
Overview section of Installing TBS calls out Kubernetes clusters including PKS, GKE and AKS..  Two paragraghs later the section is labeled "Installing on TKG/GKE/AKS.  This is minor but lacks consistency.  Also think we should be using TGKi for references to PKS.  Maybe put PKS as a footnote reference.

**Comment by sukhil-suresh** [comment]
Addressed in latest set of docs - https://docs.pivotal.io/build-service/1-0/installing.html
All PKS references have been replaced with TKGI

Thanks for raising the issue @jgalvin98 :)
