### ISSUE TITLE
Incorrect `kbld unpackage` command

### ISSUE THREAD

**Issue by mgibson1121** [pivotal-cf/docs-build-service#188]
From email from Nationwide:

On web page https://docs.pivotal.io/build-service/1-0/installing.html, in section “Relocate Images to a Registry (Air-Gapped)“ this is incorrect (must be copy/paste from a developer):

kbld unpackage -f /tmp/dev-images.lock \

  --input /tmp/packaged-images.tar \

  --repository <IMAGE-REPOSITORY> \

  --lock-output /tmp/images-relocated.loc

should be:

kbld unpackage -f /tmp/images.lock \

  --input /tmp/packaged-images.tar \

  --repository <IMAGE-REPOSITORY> \

  --lock-output /tmp/images-relocated.loc

**Comment by sukhil-suresh** [comment]
resolved with commit https://github.com/pivotal-cf/docs-build-service/commit/fbce1f866c7aa48b7d19f313008e6b64df3b44f9

deployed to prod
