### ISSUE TITLE
Link to projects-operator repo

### ISSUE THREAD

**Issue by mgibson1121** [pivotal-cf/docs-build-service#193]
* Add link to projects-operator repo in RBAC in TBS section

**Comment by sukhil-suresh** [comment]
addressed as part of https://github.com/pivotal/build-service/issues/335

**Comment by mlimonczenko** [comment]
Hello @mgibson1121,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
