### ISSUE TITLE
Add developer focused docs for local development

### ISSUE THREAD

**Issue by mgibson1121** [pivotal-cf/docs-build-service#196]
Recurring theme from doing TBS GUI interviews.  In addition to configuring the kpack image (depending on the customer), the primary use cases that were emphasized by interview participants related to dev participation with TBS centered around two areas.  The first is debugging.  Documentation around debugging is nuanced and probably needs to be discussed more.  But the local development use case seems like low hanging fruit.

Several interview subjects stressed the importance of taking a stance on the role TBS should play in the local development process.  Should TBS be just for "outer-loop" development?  Meaning that once the developer is satisfied with how their code is behaving in local environments they then check in their code to trigger TBS CI pipelines.  Or should it address "inner-loop" use cases in which the developer is rapidly iterating locally without pushing out a container image to a registry.  

Seems that for local development use cases we're currently recommending usage of the `pack` CLI.  At the very least we should document what we consider to be best practices for developers when working with TBS.  My current conception of that best practice is that developers should use use the `pack CLI` with the same kpack builder used in the image config that represents the app the dev is working on to produce a container image locally.  Once they are satisfied that the application is behaving as they expect in their local dev environment, check their code into the branch that is being monitored by the CI tool that triggers kpack.

**Comment by sukhil-suresh** [comment]
Document using kpack builder with pack cli - FAQ for TBS docs
