### ISSUE TITLE
Recommend Changing KUBECONFIG process

### ISSUE THREAD

**Issue by voor** [pivotal-cf/docs-build-service#23]
In the documentation here:

> PATH-TO-KUBECONFIG is the path to the kubeconfig configuration file on your local machine. This file is required to enable Build Service to interact with the target cluster.

I would highly encourage either showing directions for creating a service account and building a kubeconfig, or recommending a small script that does it ([here is a basic example](https://gist.github.com/voor/b201545ca36b04f83b3386b1a50bc913))

In lots of kubernetes distributions, for example PKS, the tokens that exist in those kubeconfig files will expire fairly quickly so they are not long lasting.

Additionally, that kubeconfig file might contain many clusters, and the current context might not be setup for the correct one.

**Comment by mlimonczenko** [comment]
Hello @voor,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
