### ISSUE TITLE
Updating Build Service Dependencies

### ISSUE THREAD

**Issue by mgibson1121** [pivotal-cf/docs-build-service#80]
Production:  https://docs.pivotal.io/build-service/0-2-0/updating-deps.html

Docs issues that we should cover:

https://github.com/orgs/pivotal/projects/7#card-42479030 (more direct instructions on where to go to get new stack and buildpack versions)
Suggested upgrade use cases - kp import vs. kp store add or kp stack update
This page currently points to Paketo, should point back to TBS Deps and Kashyap's GA buildpack pages in Tanzunet (Java, Go, Node)

**Comment by sampeinado** [comment]
In the "stack update" section of this page(https://docs.pivotal.io/build-service/0-2-0/updating-deps.html), Accenture (?) was confused by which <image-sha> they were supposed to use in the command examples (and where to get it). We can make more explicit why and give more detail on how to find it

**Comment by tylerphelan** [comment]
can pick back up when we know how to use the tanzu net buildpack pages/registry images

**Comment by tylerphelan** [comment]
Sorry I think I deleted this card: https://github.com/orgs/pivotal/projects/7#card-42479030

Hopefully where to find new stacks and buildpack versions is captured in the PR

**Comment by tylerphelan** [comment]
Comments from PR moved to here:
- Unfortunately, you will need to provide the sha256 of the stack images (or the tag) for this to work.

**Comment by tylerphelan** [comment]
Topics to cover here:
- Clear up image sha https://github.com/pivotal-cf/docs-build-service/issues/121
