### ISSUE TITLE
Using Tanzu Build Service - Managing Stacks

### ISSUE THREAD

**Issue by mgibson1121** [pivotal-cf/docs-build-service#84]
Production:  https://docs.pivotal.io/build-service/0-2-0/managing-stacks.html

https://github.com/orgs/pivotal/projects/7#card-42481179

**Comment by sampeinado** [comment]
Write a docs article on the scenario of `Setting up an image in TBS to rebuild on Stack updates only` -Ex. when you update specific buildpacks, nothing should happen, because you want to keep the app as stable as possible and risk breakage by middleware dependencies updating.

**Comment by sampeinado** [comment]
Write a docs article on `how to add stack metadata to a golden image manually` so that it can be used as a stack with TBS (pass on to Core Deps team?)

**Comment by sampeinado** [comment]
Add link or content from "stack use cases" readme (https://github.com/paketo-buildpacks/stacks) to TBS docs to explain which stacks are for what (and why)

**Comment by tylerphelan** [comment]
Issues to cover:
- [Setting up an image in TBS to rebuild on Stack updates only](https://github.com/pivotal-cf/docs-build-service/issues/120)
- [how to add stack metadata to a golden image manually](https://github.com/pivotal-cf/docs-build-service/issues/118)
- [Stack usecases](https://github.com/pivotal-cf/docs-build-service/issues/113)
