### ISSUE TITLE
Using Tanzu Build Service - Managing Stores

### ISSUE THREAD

**Issue by mgibson1121** [pivotal-cf/docs-build-service#85]
Prod: https://docs.pivotal.io/build-service/0-2-0/managing-stores.html

**Comment by sampeinado** [comment]
Write a docs article on `Best practices for store cleanliness`: When we do an update to the store, we don’t delete the old buildpacks. The builder always points to the highest semver. What do we suggest to customers to do to prune down or trim the buildpacks they have in the store?

**Comment by tylerphelan** [comment]
issues for [Best practices for store cleanliness](https://github.com/pivotal-cf/docs-build-service/issues/117)

**Comment by tylerphelan** [comment]
Comments moved from PR to here: 
- Would be good to call out that a user would use kp clusterstore add instead of kp import if they want to only consume certain buildpackes rather than all the buildpackages provided in the descriptor yaml

**Comment by tylerphelan** [comment]
RE: [Best practices for store cleanliness](https://github.com/pivotal-cf/docs-build-service/issues/117)

I would not expect users to need to clean their stores manually and maybe store pruning should be a new feature
