### ISSUE TITLE
Using Tanzu Build Service - Managing Builders

### ISSUE THREAD

**Issue by mgibson1121** [pivotal-cf/docs-build-service#86]
Production: https://docs.pivotal.io/build-service/0-2-0/managing-builders.html

Docs issues that we should cover:

Take into account new kpack naming schema for the builders

How to configure a builder such that images that reference that builder are only rebuilt on a stack update
https://github.com/orgs/pivotal/projects/7#card-42755725 (How to modify a meta buildpack)
https://github.com/orgs/pivotal/projects/7#card-42755679 (Removing a language family, eg. PHP from the kp import builders)

**Comment by sampeinado** [comment]
Write a docs article on `How to include a custom buildpack in a builder without messing up the builder` "Where should a custom buildpack go in the builder? What can I safely remove? 
To order this correctly, you need to know something about how the app works. How to write an order file that incorporates a custom buildpack " (pass on to buildpacks team?)

**Comment by sampeinado** [comment]
Add link or content from "stack use cases" readme (https://github.com/paketo-buildpacks/stacks) to TBS docs about which stack to use for what types of apps (and why)

**Comment by tylerphelan** [comment]
Issues for:
- [How to configure a builder such that images that reference that builder are only rebuilt on a stack update
h](https://github.com/pivotal-cf/docs-build-service/issues/120)
- [How to modify a meta buildpack](https://github.com/pivotal-cf/docs-build-service/issues/110)
- [Removing a language family, eg. PHP from the kp import builders](https://github.com/pivotal-cf/docs-build-service/issues/111)
- [How to include a custom buildpack in a builder without messing up the builder](https://github.com/pivotal-cf/docs-build-service/issues/119)
- [Stack use cases](https://github.com/pivotal-cf/docs-build-service/issues/113)

**Comment by sukhil-suresh** [comment]
> How to configure a builder such that images that reference that builder are only rebuilt on a stack update

@elenorebastian Added an entry for this at the bottom of the `Managing Builders` page. Had to cross reference this from the `Managing ClusterStacks page`
