### ISSUE TITLE
Using Tanzu Build Service - Managing Secrets 

### ISSUE THREAD

**Issue by mgibson1121** [pivotal-cf/docs-build-service#87]
Production: https://docs.pivotal.io/build-service/0-2-0/managing-secrets.html

Docs issues that we should cover:

https://github.com/orgs/pivotal/projects/7#card-42479468 (service bindings)
https://github.com/orgs/pivotal/projects/7#card-42277624 (incorrect -git flag)
https://github.com/orgs/pivotal/projects/7#card-42277616 (git-ssh workflow, don't we already document this?)
https://github.com/orgs/pivotal/projects/7#card-42342687 (known Harbor gotcha)

**Comment by tylerphelan** [comment]
Issues for:
- [Service bindings](https://github.com/pivotal-cf/docs-build-service/issues/116)
- [Git flag](https://github.com/pivotal-cf/docs-build-service/issues/123)
- [Harbor gotcha](https://github.com/pivotal-cf/docs-build-service/issues/122)
- git ssh is already documented

**Comment by tylerphelan** [comment]
Comments from PR moved here:
- Service bindings need the configmap as well.
