### ISSUE TITLE
Using Tanzu Build Service - Managing Images and Builds 

### ISSUE THREAD

**Issue by mgibson1121** [pivotal-cf/docs-build-service#88]
Production: https://docs.pivotal.io/build-service/0-2-0/managing-images.html

Docs issues we should cover:  

https://github.com/pivotal/build-service/issues/272 (Outputting kpack logs to 3rd party tool like Splunk)
https://github.com/orgs/pivotal/projects/7#card-42755825 (Env Var usage to specify a particular version of a dependency)

**Comment by sampeinado** [comment]
Write docs article on `How to use service bindings` with CNBs/TBS (maybe pass on to buildpacks team?)

**Comment by sampeinado** [comment]
Write docs article on advice on ` how to approach debugging in TBS` ex. Debugging `image apply` when image is not working

**Comment by tylerphelan** [comment]
Added issue for the additional topics to cover: https://github.com/pivotal-cf/docs-build-service/issues/103

**Comment by tylerphelan** [comment]
issues for topics covered:
- [Env Var usage to specify a particular version of a dependency](https://github.com/pivotal-cf/docs-build-service/issues/109)
- [Service bindings](https://github.com/pivotal-cf/docs-build-service/issues/116)

**Comment by tylerphelan** [comment]
For note: when we say "Env Var usage to specify a particular version of a dependency" I'm guess we're talking about something like `GO_VERSION` to pick the version of Go the Go buildpack will provide. 

As far as I can tell this can only be done with `buildpack.yml` these days. Some configuration can be done with env vars such as `BP_GO_TARGETS`, but dependency version is usually via `buildpack.yml`

**Comment by tylerphelan** [comment]
I actually don't think
