### ISSUE TITLE
Using Tanzu Build Service With Projects

### ISSUE THREAD

**Issue by mgibson1121** [pivotal-cf/docs-build-service#89]
Production:  https://docs.pivotal.io/build-service/0-2-0/tbs-with-projects.html

**Comment by tylerphelan** [comment]
Moved comment from PR to here:

What you've written broadly looks good, but I wonder if there's a bigger opportunity here to discuss RBAC more broadly. We have a lot of customers ask about best practices around RBAC and TBS. Maybe something like:

"Given that Tanzu Build Service supports functionality most customers would likely want to restrict to only certain users, we encourage utilization of RBAC as a best practice if Tanzu Build Service is to be broadly deployed for usage by many users.

Tanzu Build Service does not ship with a prescribed RBAC method given the wide variety of customer preference for managing these policies. But the "Projects Operator" is an open source solution that can be used to enforce RBAC policy in Kubernetes namespaces. The product team uses the "Projects Operator" in its development of Tanzu Build Service."
